# Generated by Django 5.2.14 on 2026-06-02 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminUser',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('role', models.CharField(max_length=80)),
                ('company', models.CharField(max_length=140)),
                ('status', models.CharField(default='Active', max_length=40)),
                ('mfa', models.BooleanField(default=False)),
                ('last_seen', models.CharField(default='Just now', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='NotificationRule',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('channel', models.CharField(max_length=40)),
                ('title', models.CharField(max_length=140)),
                ('audience', models.CharField(max_length=140)),
                ('status', models.CharField(default='Enabled', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['channel', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=60)),
                ('customer', models.CharField(max_length=140)),
                ('amount', models.CharField(max_length=40)),
                ('method', models.CharField(max_length=100)),
                ('status', models.CharField(default='Succeeded', max_length=60)),
                ('captured', models.BooleanField(default=True)),
                ('settlement', models.CharField(default='Pending', max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at', 'customer'],
            },
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('provider', models.CharField(max_length=60)),
                ('mode', models.CharField(default='Test', max_length=40)),
                ('capabilities', models.JSONField(default=list)),
                ('status', models.CharField(default='Connected', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['provider'],
            },
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=80)),
                ('price', models.CharField(max_length=40)),
                ('interval', models.CharField(default='Monthly', max_length=40)),
                ('customers', models.PositiveIntegerField(default=0)),
                ('features', models.JSONField(default=list)),
                ('status', models.CharField(default='Public', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('customer', models.CharField(max_length=140)),
                ('plan', models.CharField(max_length=80)),
                ('status', models.CharField(default='Active', max_length=40)),
                ('billing_cycle', models.CharField(default='Monthly', max_length=40)),
                ('renewal_date', models.DateField()),
                ('mrr', models.CharField(max_length=40)),
                ('payment_method', models.CharField(max_length=80)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['renewal_date', 'customer'],
            },
        ),
        migrations.CreateModel(
            name='SystemSetting',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('group', models.CharField(max_length=80)),
                ('label', models.CharField(max_length=140)),
                ('value', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['group', 'label'],
            },
        ),
    ]
