# Generated by Django 5.2.14 on 2026-06-02 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoggedInUser',
            fields=[
                ('id', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('avatar_url', models.URLField(blank=True)),
                ('provider', models.CharField(default='google', max_length=40)),
                ('google_subject', models.CharField(blank=True, max_length=120)),
                ('last_login_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-last_login_at'],
            },
        ),
    ]
