ADMIN_DASHBOARD = {
    "tenants": [
        {"id": "tnt_atlas", "name": "Atlas Finance", "subdomain": "atlas", "status": "Active"},
        {"id": "tnt_bright", "name": "BrightOps", "subdomain": "bright", "status": "Active"},
        {"id": "tnt_north", "name": "Northstar Labs", "subdomain": "northstar", "status": "Active"},
        {"id": "tnt_pixel", "name": "Pixel Foundry", "subdomain": "pixel", "status": "Suspended"},
    ],
    "metrics": [
        {"label": "Monthly recurring revenue", "value": "$186.2K", "change": "+14.8%", "tone": "positive"},
        {"label": "Active users", "value": "12,486", "change": "+9.1%", "tone": "positive"},
        {"label": "Net retention", "value": "118%", "change": "+3.4%", "tone": "positive"},
        {"label": "Failed payments", "value": "27", "change": "-11.5%", "tone": "positive"},
    ],
    "users": [
        {
            "id": "usr_1001",
            "tenant_id": "tnt_atlas",
            "name": "Maya Chen",
            "email": "maya@atlasfinance.com",
            "role": "Owner",
            "company": "Atlas Finance",
            "status": "Active",
            "mfa": True,
            "last_seen": "2 minutes ago",
        },
        {
            "id": "usr_1002",
            "tenant_id": "tnt_bright",
            "name": "Arjun Mehta",
            "email": "arjun@brightops.io",
            "role": "Billing admin",
            "company": "BrightOps",
            "status": "Invited",
            "mfa": False,
            "last_seen": "Pending invite",
        },
        {
            "id": "usr_1003",
            "tenant_id": "tnt_north",
            "name": "Elena Brooks",
            "email": "elena@northstar.dev",
            "role": "Support lead",
            "company": "Northstar Labs",
            "status": "Active",
            "mfa": True,
            "last_seen": "18 minutes ago",
        },
        {
            "id": "usr_1004",
            "tenant_id": "tnt_pixel",
            "name": "Daniel Park",
            "email": "daniel@pixelfoundry.studio",
            "role": "Member",
            "company": "Pixel Foundry",
            "status": "Suspended",
            "mfa": False,
            "last_seen": "12 days ago",
        },
    ],
    "plans": [
        {
            "id": "plan_starter",
            "name": "Starter",
            "price": "$29",
            "interval": "Monthly",
            "customers": 184,
            "features": ["5 seats", "Email support", "Basic analytics"],
            "status": "Public",
        },
        {
            "id": "plan_growth",
            "name": "Growth",
            "price": "$99",
            "interval": "Monthly",
            "customers": 392,
            "features": ["25 seats", "Usage alerts", "Advanced reports"],
            "status": "Public",
        },
        {
            "id": "plan_enterprise",
            "name": "Enterprise",
            "price": "Custom",
            "interval": "Annual",
            "customers": 76,
            "features": ["SSO/SAML", "SCIM", "Dedicated CSM"],
            "status": "Approval only",
        },
    ],
    "subscriptions": [
        {
            "id": "sub_atlas_001",
            "tenant_id": "tnt_atlas",
            "customer": "Atlas Finance",
            "plan": "Enterprise",
            "status": "Active",
            "billing_cycle": "Annual",
            "renewal_date": "2026-08-14",
            "mrr": "$24,800",
            "payment_method": "Stripe card",
        },
        {
            "id": "sub_bright_008",
            "tenant_id": "tnt_bright",
            "customer": "BrightOps",
            "plan": "Growth",
            "status": "Past due",
            "billing_cycle": "Monthly",
            "renewal_date": "2026-06-05",
            "mrr": "$7,920",
            "payment_method": "Razorpay UPI",
        },
        {
            "id": "sub_north_004",
            "tenant_id": "tnt_north",
            "customer": "Northstar Labs",
            "plan": "Enterprise",
            "status": "Active",
            "billing_cycle": "Annual",
            "renewal_date": "2026-11-21",
            "mrr": "$18,600",
            "payment_method": "Wire transfer",
        },
        {
            "id": "sub_pixel_011",
            "tenant_id": "tnt_pixel",
            "customer": "Pixel Foundry",
            "plan": "Starter",
            "status": "Trialing",
            "billing_cycle": "Monthly",
            "renewal_date": "2026-06-16",
            "mrr": "$348",
            "payment_method": "Stripe card",
        },
    ],
    "payments": [
        {
            "id": "pay_9Q8A11",
            "tenant_id": "tnt_atlas",
            "provider": "Stripe",
            "customer": "Atlas Finance",
            "amount": "$24,800",
            "method": "Visa ending 4242",
            "status": "Succeeded",
            "captured": True,
            "settlement": "2026-06-04",
        },
        {
            "id": "pay_RZP_5602",
            "tenant_id": "tnt_bright",
            "provider": "Razorpay",
            "customer": "BrightOps",
            "amount": "$7,920",
            "method": "UPI mandate",
            "status": "Retry scheduled",
            "captured": False,
            "settlement": "Pending",
        },
        {
            "id": "pay_PP_2026",
            "tenant_id": "tnt_north",
            "provider": "PayPal",
            "customer": "Northstar Labs",
            "amount": "$18,600",
            "method": "Business account",
            "status": "Succeeded",
            "captured": True,
            "settlement": "2026-06-06",
        },
        {
            "id": "pay_MAN_334",
            "tenant_id": "tnt_pixel",
            "provider": "Manual invoice",
            "customer": "Pixel Foundry",
            "amount": "$348",
            "method": "Payment link",
            "status": "Awaiting payment",
            "captured": False,
            "settlement": "Not settled",
        },
    ],
    "analytics": {
        "revenue": [
            {"month": "Jan", "value": 108},
            {"month": "Feb", "value": 122},
            {"month": "Mar", "value": 139},
            {"month": "Apr", "value": 151},
            {"month": "May", "value": 168},
            {"month": "Jun", "value": 186},
        ],
        "funnels": [
            {"label": "Trials started", "value": "1,420", "change": "+18%"},
            {"label": "Activated teams", "value": "842", "change": "+11%"},
            {"label": "Paid conversions", "value": "268", "change": "+6%"},
        ],
        "segments": [
            {"name": "Expansion ready", "count": 184, "signal": "Seat usage above 85%", "priority": "High"},
            {"name": "Churn watch", "count": 37, "signal": "Low activity and failed renewal", "priority": "Urgent"},
            {"name": "Onboarding", "count": 92, "signal": "Setup checklist incomplete", "priority": "Medium"},
        ],
    },
    "notifications": [
        {"id": "ntf_001", "channel": "Email", "title": "Payment failure digest", "audience": "Billing admins", "status": "Enabled"},
        {"id": "ntf_002", "channel": "Webhook", "title": "subscription.updated", "audience": "Finance systems", "status": "Healthy"},
        {"id": "ntf_003", "channel": "SMS", "title": "Trial ending reminder", "audience": "Workspace owners", "status": "Paused"},
        {"id": "ntf_004", "channel": "In-app", "title": "Security review required", "audience": "Super admins", "status": "Enabled"},
    ],
    "settings": [
        {"tenant_id": "tnt_atlas", "group": "Security", "label": "Require MFA for admins", "value": "Enabled"},
        {"tenant_id": "tnt_bright", "group": "Billing", "label": "Smart payment retries", "value": "3 attempts over 7 days"},
        {"tenant_id": "tnt_north", "group": "Integrations", "label": "Payment gateways", "value": "Stripe, Razorpay, PayPal"},
        {"tenant_id": "tnt_pixel", "group": "Data", "label": "Audit log retention", "value": "365 days"},
        {"tenant_id": "tnt_atlas", "group": "Notifications", "label": "Webhook signing", "value": "Rotated monthly"},
    ],
    "payment_methods": [
        {"provider": "Stripe", "mode": "Test", "capabilities": ["Cards", "Invoices", "Refunds"], "status": "Connected"},
        {"provider": "Razorpay", "mode": "Test", "capabilities": ["UPI", "Payment links", "Subscriptions"], "status": "Connected"},
        {"provider": "PayPal", "mode": "Sandbox", "capabilities": ["Wallet", "Cross-border"], "status": "Ready"},
    ],
}
